name:                hscheme
version:             0.1.0.0
#synopsis:
#description:
#homepage:            https://github.com/githubuser/AdventOfCode2020#readme
#license:             BSD3
#license-file:        LICENSE
author:              David Voigt
maintainer:          david.voigt1998@gmail.com
copyright:           2020 David Voigt
category:            None
build-type:          Simple
extra-source-files:  README.md

dependencies:
- base >= 4.7 && < 5

default-extensions:
- TypeOperators
- RecordWildCards
- LambdaCase

library:
  source-dirs:  src
  dependencies:
  - parsec
  - mtl

executables:
  hscheme-repl:
    main: Main.hs
    source-dirs: app
    dependencies:
    - hscheme